"use server";

import { prisma } from "@/core/prisma";
import { revalidatePath } from "next/cache";

export async function saveSettings(formData: FormData) {
    try {
        const payload = Object.fromEntries(formData.entries());

        for (const [key, value] of Object.entries(payload)) {
            if (typeof value === "string") {
                await prisma.setting.upsert({
                    where: { key },
                    update: { value, updatedAt: new Date() },
                    create: { key, value, description: `Autogenerated for ${key}` }
                });
            }
        }

        revalidatePath('/admin/settings');
        return { success: true };
    } catch (error) {
        console.error("Settings save error:", error);
        return { success: false, error: "Failed to save settings" };
    }
}
